openapi: 3.0.0
info:
  version: '1.0'
  title: "D'Art OpenAPI 3.0"
  description: API for Viewing and Publishing Digital Art.
  license:
    name: MIT
servers:
  - url: http://localhost:8000/api/v1
    description: Localhost
paths:
  /users:
    post:
      description: >-
        Creates a new user in the system.
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - username
                - password
              properties:
                email:
                  type: string
                  description: 'Email address of the user'
                username:
                  type: string
                  description: 'Username for the profile'
                password:
                  type: string
                  description: 'Password for authentication'
      responses:
        '201':
          description: 'User created. Link in the Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link to the newly created user.
  /login:
    post:
      description: >-
        Logs in an existing user and returns a session token.
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: 'Username or email address'
                password:
                  type: string
                  description: 'User password'
      responses:
        '200':
          description: 'Login successful'
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: 'Session token'
  /dartworks:
    get:
      description: >-
        Gets the list of active D'ArtWorks.
      summary: View active D'ArtWorks
      parameters:
        - in: query
          name: hashtag
          schema:
            type: string
          description: 'Filter D\'ArtWorks by hashtag'
        - in: query
          name: artist
          schema:
            type: string
          description: 'Filter D\'ArtWorks by artist username'
      responses:
        '200':
          description: 'Collection of D\'ArtWorks'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DArtWork'
    post:
      description: >-
        Creates and publishes a new D'ArtWork.
      summary: Publish a D'ArtWork
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DArtWork'
      responses:
        '201':
          description: "D'ArtWork published. Link in the Location header"
          headers:
            'Location':
              schema:
                type: string
              description: Link to the newly created D'ArtWork.

  /users/{username}:
    get:
      description: >-
        Gets details of a user profile.
      summary: View user profile
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: 'Username of the user profile'
      responses:
        '200':
          description: 'User profile details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
components:
  schemas:
    DArtWork:
      type: object
      required:
        - title
        - latitude
        - longitude
        - assetUrl
      properties:
        title:
          type: string
          description: "Title of the D'ArtWork"
        description:
          type: string
          description: "Description of the D'ArtWork"
        latitude:
          type: number
          description: 'Latitude position'
        longitude:
          type: number
          description: 'Longitude position'
        assetUrl:
          type: string
          description: 'URL of to the 3D model, image, or animation'
        hashtags:
          type: array
          items:
            type: string
          description: 'Associated Hashtags'
        artist:
          type: string
          description: 'Artist name'
    UserProfile:
      type: object
      required:
        - username
      properties:
        username:
          type: string
          description: 'Username of the user'
        bio:
          type: string
          description: 'Biography of the user'
        badges:
          type: string
          description: 'Displayed Badge'
        published:
          type: array
          items:
            $ref: '#/components/schemas/DArtWork'
          description: "D'ArtWorks published by the user"
